name: auto-push

on: 
  push:
    branches:
     - master
  schedule:
    - cron: '0 2,4,6,8,10,12,14,16,18,20,22 * * *'
    - cron: '0 15 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      
      - name: Setup node version
        uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Taipei"

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: run deploy
        env:
          API_DOMAIN: ${{ secrets.API_DOMAIN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: "pnpm install && pnpm run deploy"

      - name: send tips
        if: github.event.schedule == '0 15 * * *'
        env:
          NOTIFY_URI: ${{ secrets.NOTIFY_URI}}
        run: "pnpm run notify"